name:                easy-logger
version:             0.1.0.0
github:              "schnecki/easy-logger"
license:             BSD3
author:              "Manuel Schneckenreither"
maintainer:          "manuel.schnecki@gmail.com"
copyright:           "2021 Manuel Schneckenreither"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/easy-logger#readme>

dependencies:
- base >= 4.7 && < 5
- unix-time
- unix-compat
- text
- array
- template-haskell
- bytestring
- auto-update
- containers


library:
  source-dirs: src

tests:
  easy-logger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - easy-logger
    - QuickCheck
    - quickcheck-assertions
    - hspec
